# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_level',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
